task: custom_task_2
test_split: test
fewshot_split: train
fewshot_config:
  sampler: first_n
doc_to_text: "질문: {{question}}\n답변:"
doc_to_target: "{{answer}}"
description: "커스텀 태스크 2 - 질문답변 평가"
dataset_path: json
dataset_kwargs:
  data_files:
    train: "../../datasets/raw/custom_benchmark/train.jsonl"
    test: "../../datasets/raw/custom_benchmark/test.jsonl"
output_type: generate_until
generation_kwargs:
  until: ["\n"]
  max_gen_toks: 100
filter_list:
  - name: "whitespace_cleanup"
    filter:
      - function: "regex"
        regex_pattern: "^\\s*(.*)$"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: 1.0
