site_name: vLLM Evaluation Benchmark
repo_name: thakicloud/vllm-eval-public
repo_url: https://github.com/thakicloud/vllm-eval-public
site_url: https://thakicloud.github.io/vllm-eval-public
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: material/chart-line-variant  # Performance/evaluation related icon
    repo: fontawesome/brands/github     # GitHub icon for repository link
  favicon: assets/favicon.png          # Custom favicon (optional)
  features:
    - navigation.tabs          # Enable top-level tabs in header
    - navigation.tabs.sticky   # Keep tabs visible when scrolling
    - navigation.sections      # Show sections in navigation
    - navigation.expand        # Expand navigation sections by default
    - navigation.indexes       # Enable navigation indexes for sections
    - navigation.top           # Add "Back to top" button
    - navigation.tracking      # Update URL with active anchor
    - navigation.footer        # Add next/previous page navigation at bottom
    - navigation.instant       # Instant loading for faster navigation
    - toc.integrate           # Integrate table of contents with navigation
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Production Guide: vllm-eval-prd.md
  - CLI Guide:
    - Overview: cli/overview.md
    - Commands Reference: cli/commands.md
    - Configuration: cli/configuration.md
    - Troubleshooting: cli/troubleshooting.md
  - Architecture:
    - System Overview: architecture/system-overview.md
    - Data Flow: architecture/data-flow.md
    - Component Diagram: architecture/component-diagram.md
    - Deployment Guide: architecture/deployment-guide.md
    - Security Model: architecture/security-model.md
  - Developer Guide:
    - Quick Start: developer/quick-start.md
    - Development Setup: developer/development-setup.md
    - Coding Standards: developer/coding-standards.md
    - Testing Guide: developer/testing-guide.md
    - CI/CD Pipeline: developer/ci-cd-pipeline.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Benchmark Configuration: user/benchmark-configuration.md
    - Result Interpretation: user/result-interpretation.md
    - Custom Metrics: user/custom-metrics.md
  - API Reference:
    - Evalchemy API: api/evalchemy-api.md
    - Deepeval API: api/deepeval-api.md
    - NVIDIA Eval API: api/nvidia-eval-api.md
    - VLLM Benchmark API: api/vllm-benchmark-api.md
  - Operations:
    - Monitoring Guide: operations/monitoring-guide.md
    - Troubleshooting: operations/troubleshooting.md
    - Performance Tuning: operations/performance-tuning.md
    - Backup and Recovery: operations/backup-recovery.md
    - Scaling Guide: operations/scaling-guide.md
  - Guides:
    - CI/CD Guide: how-to-CICD.md
    - Adding Benchmarks: how-to-add-benchmark.md
    - Local Testing: local-testing-guide.md
    - Local VLLM Evaluation: local-vllm-evaluation-guide.md
    - Standard Evalchemy: standard-evalchemy-guide.md
  - Contributing: CONTRIBUTING.md
