site_name: VLLM 모델 성능 자동 평가 시스템
repo_name: thakicloud/vllm-eval-public
repo_url: https://github.com/thakicloud/vllm-eval-public

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - 프로덕션 가이드: vllm-eval-prd.md
  - Architecture:
    - System Overview: architecture/system-overview.md
    - Data Flow: architecture/data-flow.md
    - Component Diagram: architecture/component-diagram.md
    - Deployment Guide: architecture/deployment-guide.md
    - Security Model: architecture/security-model.md
  - Developer Guide:
    - Quick Start: developer/quick-start.md
    - Development Setup: developer/development-setup.md
    - Coding Standards: developer/coding-standards.md
    - Testing Guide: developer/testing-guide.md
    - CI/CD Pipeline: developer/ci-cd-pipeline.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Benchmark Configuration: user/benchmark-configuration.md
    - Result Interpretation: user/result-interpretation.md
    - Custom Metrics: user/custom-metrics.md
  - API Reference:
    - Evalchemy API: api/evalchemy-api.md
    - Deepeval API: api/deepeval-api.md
    - NVIDIA Eval API: api/nvidia-eval-api.md
    - VLLM Benchmark API: api/vllm-benchmark-api.md
  - Operator Manual:
    - Monitoring Guide: operations/monitoring-guide.md
    - Troubleshooting: operations/troubleshooting.md
    - Performance Tuning: operations/performance-tuning.md
    - Backup and Recovery: operations/backup-recovery.md
    - Scaling Guide: operations/scaling-guide.md
  - 기여하기: CONTRIBUTING.md
