# Job for running VLLM evaluation
apiVersion: batch/v1
kind: Job
metadata:
  name: vllm-benchmark
  labels:
    app: vllm-eval
spec:
  # Cleanup after completion (2 minutes)
  ttlSecondsAfterFinished: 120
  
  template:
    metadata:
      labels:
        app: vllm-eval
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodepool
                    operator: NotIn
                    values:
                      - "gpu"
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: vllm-benchmark
          image: ghcr.io/thakicloud/vllm-benchmark-linux:latest 
          imagePullPolicy: Always
          
          # Resource limits
          resources:
            requests: 
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "5Gi"

          # Environment variables (see Dockerfile)
          env:
            - name: MODEL_ENDPOINT
              value: "http://vllm.vllm:8000" # Use K8s Service name
              # value: "http://opt125m-inference-vllm-inference.vllm-system:8000" # Use K8s Service name
#            - name: MODEL_NAME
#              value: "Qwen/Qwen3-30B-A3B"
            - name: RANDOM_INPUT_LEN
              value: "512"
            - name: MAX_CONCURRENCY
              value: "1"
            - name: BACKEND_API
              value: "http://10.7.60.71:10301"
            - name: CONFIG_PATH
              value: "/app/configs/eval_config.json"
          