name: CI - Lint & Test

on:
  push:
    branches-ignore:
      - 'main'
      - 'hotfix/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    name: 游냀 Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout repository
        uses: actions/checkout@v4
      - name: 游닍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 游닍 Install linters
        run: pip install flake8 black
      - name: 游댌 Run Black (format check)
        run: black --check .
        continue-on-error: true
      - name: 游댌 Run flake8
        run: flake8 .
        continue-on-error: true

  shell-lint:
    name: 游닆 Shell Script Lint
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout repository
        uses: actions/checkout@v4
      - name: 游댌 Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './'
        continue-on-error: true

  dockerfile-lint:
    name: 游냡 Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout repository
        uses: actions/checkout@v4
      - name: 游댌 Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: 'docker/*.Dockerfile'
          no-fail: true

  markdown-lint:
    name: 游닇 Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout repository
        uses: actions/checkout@v4
      - name: 游닍 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: 游닍 Install markdownlint
        run: npm install -g markdownlint-cli
      - name: 游닇 Create markdownlint config
        run: |
          cat > .markdownlint.json << 'EOF'
          {
            "MD013": false,
            "MD033": false,
            "MD034": false,
            "MD036": false,
            "MD041": false
          }
          EOF
      - name: 游댌 Run Markdown lint
        run: |
          markdownlint '**/*.md' --config .markdownlint.json || echo "丘멆잺 Markdown lint issues found, but continuing..."

  yaml-lint:
    name: 游늯 YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Checkout repository
        uses: actions/checkout@v4
      - name: 游닍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: 游닍 Install yamllint
        run: pip install yamllint
      - name: 游댌 Run YAML lint
        run: |
          yamllint -d relaxed . || echo "丘멆잺 YAML lint issues found, but continuing..."
