name: 🚀 Deploy NVIDIA Eval

on:
  push:
    tags:
      - 'nvidia-eval-v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-nvidia-eval:
    name: 🚀 Deploy NVIDIA Eval to Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: ⚙️ Set lowercase image name
        id: set_lowercase_name
        run: echo "name=$(echo '${{ env.IMAGE_NAME }}-nvidia-eval' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: 🔑 Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐦 Install crane
        uses: imjasonh/setup-crane@v0.4

      - name: 🔎 Find Latest Release Image
        id: find_latest_image
        run: |
          IMAGE_NAME_LOWERCASE=${{ steps.set_lowercase_name.outputs.name }}
          LATEST_RELEASE_TAG=$(crane ls ${{ env.REGISTRY }}/${IMAGE_NAME_LOWERCASE} | grep "release-" | sort -r | head -n 1)
          if [ -z "$LATEST_RELEASE_TAG" ]; then
            echo "Error: No release-* image found for ${{ env.REGISTRY }}/${IMAGE_NAME_LOWERCASE}."
            exit 1
          fi
          echo "Found latest release tag: $LATEST_RELEASE_TAG"
          echo "latest_release_tag=${LATEST_RELEASE_TAG}" >> $GITHUB_OUTPUT

      - name: 🏷️ Tag Existing Image
        id: tag_image
        run: |
          VERSION_TAG=$(echo "${{ github.ref_name }}" | sed -E 's/^nvidia-eval-(v.*)$/\1/')
          IMAGE_NAME_LOWERCASE=${{ steps.set_lowercase_name.outputs.name }}
          SRC_IMAGE="${{ env.REGISTRY }}/${IMAGE_NAME_LOWERCASE}:${{ steps.find_latest_image.outputs.latest_release_tag }}"
          
          echo "Tagging ${SRC_IMAGE} with ${VERSION_TAG}"
          crane tag "${SRC_IMAGE}" "${VERSION_TAG}"
          
          echo "new_tag=${VERSION_TAG}" >> $GITHUB_OUTPUT

      - name: 📥 Checkout Manifest Repository
        uses: actions/checkout@v4
        with:
          repository: ThakiCloud/vllm-manifests-public
          token: ${{ secrets.MANIFESTS_SECRET }}
          ref: main

      - name: 📝 Update Image Tag in Manifest
        run: |
          IMAGE_NAME_LOWERCASE=${{ steps.set_lowercase_name.outputs.name }}
          MANIFEST_FILE=vllm-eval/nvidia-eval-job.yaml
          
          echo "Updating image in $MANIFEST_FILE to ${{ env.REGISTRY }}/${IMAGE_NAME_LOWERCASE}:${{ steps.tag_image.outputs.new_tag }}"
          
          if [ -f "$MANIFEST_FILE" ]; then
            sed -E "s|(image:\s*).*$|\1${{ env.REGISTRY }}/${IMAGE_NAME_LOWERCASE}:${{ steps.tag_image.outputs.new_tag }}|" -i $MANIFEST_FILE
          else
            echo "Error: Manifest file $MANIFEST_FILE not found."
            exit 1
          fi

      - name: 🚀 Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "CI: update nvidia-eval image to ${{ github.ref_name }} (${{ github.sha }})"
          branch: main
          commit_options: '--no-verify'
          commit_user_name: 'yunjae-park1111'
          commit_user_email: 'yunjae.park@thakicloud.co.kr'

      - name: ✅ Deployment Summary
        run: |
          echo "### 🚀 NVIDIA Eval Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ env.REGISTRY }}/${{ steps.set_lowercase_name.outputs.name }}:${{ steps.tag_image.outputs.new_tag }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Triggering Tag:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Supported Benchmarks:**" >> $GITHUB_STEP_SUMMARY
          echo "- 🧮 AIME (American Invitational Mathematics Examination)" >> $GITHUB_STEP_SUMMARY
          echo "- 💻 LiveCodeBench (Live Coding Benchmark)" >> $GITHUB_STEP_SUMMARY
          echo "**Usage Examples:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "# AIME Evaluation" >> $GITHUB_STEP_SUMMARY
          echo "docker run -e EVAL_TYPE=aime -e MODEL_NAME=qwen3-8b nvidia-eval" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# LiveCodeBench Evaluation" >> $GITHUB_STEP_SUMMARY
          echo "docker run -e EVAL_TYPE=lcb -e MODEL_NAME=qwen3-8b nvidia-eval" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "# Both Evaluations" >> $GITHUB_STEP_SUMMARY
          echo "docker run -e EVAL_TYPE=both -e MODEL_NAME=qwen3-8b nvidia-eval" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY 